virtualbox reuse existing bootimage-auto.iso
Allow ./setup.sh to run without requiring a path to ISO image
parameter. This enables re-using existing bootimage-auto.iso to
rebuild the lab from scratch without going through the prepare
ISO stage.

diff --git a/templates/vbox/setup.tmpl b/templates/vbox/setup.tmpl
--- a/templates/vbox/setup.tmpl
+++ b/templates/vbox/setup.tmpl
@@ -176,7 +176,9 @@ ERROR!   sudo usermod -a -G vboxusers $USER
 EOF
     fi
     check_dependencies
-    prepare_bootimage ${ISO_PATH}
+    if [[ -n "${ISO_PATH}" ]]; then
+        prepare_bootimage ${ISO_PATH}
+    fi
     setup_vbox
     setup_environment
     echo "\nDONE!"
@@ -184,8 +186,7 @@ EOF
 
 ISO_PATH=$1
 if [[ -z "${ISO_PATH}" ]]; then
-    echo 'ERROR! missing iso path' >&2
-    exit 1
+    echo 'WARNING! missing iso path. Will use existing bootimage-auto.iso (if present)' >&2
 fi
 main
 {{- end }}
